spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leaf?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&autoReconnect=true&useSSL=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    druid:
      initial-size: 2
      min-idle: 2
      max-active: 5
      max-wait: 60000
mybatis:
  configuration:
    default-executor-type: reuse
    map-underscore-to-camel-case: true

sf:
  datacenterId: 0
  machineId: 0
